export enum COLORS {
  BASIC_BLACK = '#2f2f2f',
  MELON_GREEN = '#E4EDBE',
  OLIVE_GREEN = '#B3C32D',
  BUTTON_GREEN = '#CDDA6C',
  WHITE = '#ffffff',
  FOOTER_BLACK = '#1C1C1C',
  FOOTER_LIGHT_GRAY = '#EAEAEA',
  FOOTER_MEDIUM_GRAY = '#C1C1C1',
}
